'use strict';

/**
 * Every shape of invoice MyVault has been taught to read.
 *
 * The reader was built against Greek and English invoices, and it showed: a
 * French one was refused outright for having no table in it, a Spanish one lost
 * its code and discount columns, and a supplier who prints the discount as
 * money rather than as a rate had every line of the delivery disagreeing with
 * the paper — and the cost that reached the shop's price list was the
 * undiscounted one.
 *
 * Every fixture here is one of those. They are generated by
 * scripts/make-invoice-fixtures.mjs and none of them is a real invoice to a real
 * shop: the names, the numbers and the products are all invented.
 *
 * The last one is the one MyVault cannot read, and it is here on purpose. A
 * heading wide enough to wrap onto three rows still defeats it; what this pins
 * is that it says so and refuses the file, rather than importing the nonsense
 * it used to make of it.
 */
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { extractPdfText } = require('../electron/pdf-text');
const { readInvoice } = require('../electron/invoice-read');

let passed = 0;
const ok = (label) => { passed += 1; console.log('  ok  ' + label); };

const read = async (name) => readInvoice(
  await extractPdfText(fs.readFileSync(path.join(__dirname, 'fixtures', `${name}.pdf`))),
);

/** Every figure the shop would compare against the paper in their hand. */
function expectLines(invoice, expected, what) {
  assert.strictEqual(invoice.lines.length, expected.length, `${what}: line count`);
  expected.forEach((want, i) => {
    const line = invoice.lines[i];
    assert.strictEqual(line.description, want.description, `${what}: name of line ${i + 1}`);
    assert.strictEqual(line.quantity, want.quantity, `${what}: quantity of line ${i + 1}`);
    assert.strictEqual(line.unitPrice, want.unitPrice, `${what}: price of line ${i + 1}`);
    assert.strictEqual(line.discount, want.discount, `${what}: discount of line ${i + 1}`);
    assert.strictEqual(line.vatRate, want.vatRate, `${what}: VAT rate of line ${i + 1}`);
    assert.strictEqual(line.total, want.total, `${what}: total of line ${i + 1}`);
  });
  assert.deepStrictEqual(invoice.warnings, [], `${what}: nothing should be flagged`);
}

(async () => {
  console.log('\n▶ invoice layouts');

  // ------------------------------------------------------------------ German
  {
    const invoice = await read('german');
    assert.strictEqual(invoice.supplier, 'Getränke Grosshandel GmbH');
    assert.strictEqual(invoice.number, '2026-0442');
    // 14.08.2026 — dots, not slashes, and day first.
    assert.strictEqual(invoice.date, '2026-08-14');
    expectLines(invoice, [
      { description: 'Mineralwasser 1L', quantity: 24, unitPrice: 0.45, discount: 0, vatRate: 19, total: 10.8 },
      { description: 'Apfelsaft naturtrüb 1L', quantity: 12, unitPrice: 1.2, discount: 0, vatRate: 19, total: 14.4 },
      { description: 'Kaffeebohnen 1kg', quantity: 6, unitPrice: 12.5, discount: 0, vatRate: 7, total: 75 },
    ], 'german');
    assert.strictEqual(invoice.totals.net, 100.2);
    assert.strictEqual(invoice.netCheck, true);
    ok('a German invoice: Menge, Einzelpreis, MwSt, and two rates on one page');
  }

  // ----------------------------------------------------------------- Spanish
  {
    const invoice = await read('spanish');
    assert.strictEqual(invoice.number, 'F-2026/318');
    assert.ok(invoice.columns.includes('code'), '"Código" is the code column');
    assert.ok(invoice.columns.includes('discount'), 'and "Dto %" is the discount');
    expectLines(invoice, [
      { description: 'Aceite de oliva 1L', quantity: 12, unitPrice: 4.8, discount: 0, vatRate: 10, total: 57.6 },
      { description: 'Arroz bomba 1kg', quantity: 20, unitPrice: 2.15, discount: 5, vatRate: 10, total: 40.85 },
    ], 'spanish');
    // "Base imponible" is the net, and nothing else on the page is.
    assert.strictEqual(invoice.totals.net, 98.45);
    ok('a Spanish invoice, down to the accented headings and the base imponible');
  }

  // ------------------------------------------------------------------ French
  {
    const invoice = await read('french');
    assert.strictEqual(invoice.supplier, 'Établissements Dubois SARL');
    assert.strictEqual(invoice.number, '2026-1177');
    expectLines(invoice, [
      { description: 'Farine T55 5kg', quantity: 10, unitPrice: 3.9, discount: 0, vatRate: 5.5, total: 39 },
      { description: 'Sucre en poudre 1kg', quantity: 15, unitPrice: 1.1, discount: 0, vatRate: 5.5, total: 16.5 },
    ], 'french');
    assert.strictEqual(invoice.totals.net, 55.5);
    assert.strictEqual(invoice.totals.vat, 3.05);
    ok('a French invoice, which was refused outright before the accents came off');
  }

  // ------------------------------------- a unit in the cell, and big numbers
  {
    const invoice = await read('units-and-thousands');
    expectLines(invoice, [
      { description: 'Flour, plain', quantity: 12, unitPrice: 1.95, discount: 0, vatRate: 20, total: 23.4 },
      { description: 'Sunflower oil 5L', quantity: 6, unitPrice: 8.4, discount: 0, vatRate: 20, total: 50.4 },
      { description: 'Rice 25kg sack', quantity: 80, unitPrice: 17.25, discount: 0, vatRate: 20, total: 1380 },
    ], 'units-and-thousands');
    // "1,380.00" is one thousand three hundred and eighty, not one and a third.
    assert.strictEqual(invoice.totals.net, 1453.8);
    ok('"12 pcs" is a quantity of twelve, and "1,380.00" is not one point three eight');
  }

  // --------------------------------------------- a discount printed as money
  {
    const invoice = await read('money-discount');
    // €1,80 off twenty at ninety cents is ten per cent, and the line then
    // agrees with the paper — which is the whole point of working it back out.
    expectLines(invoice, [
      { description: 'Χαρτοπετσέτες 100τεμ', quantity: 20, unitPrice: 0.9, discount: 10, vatRate: 24, total: 16.2 },
      { description: 'Ποτήρια πλαστικά 50τεμ', quantity: 30, unitPrice: 1.4, discount: 10, vatRate: 24, total: 37.8 },
    ], 'money-discount');
    ok('a discount printed in money becomes the rate the invoice did not print');
  }

  // ------------------------------------------- a supplier who charges one rate
  {
    const invoice = await read('no-vat-column');
    assert.ok(!invoice.columns.includes('vatRate'), 'there is no VAT column to find');
    expectLines(invoice, [
      { description: 'Baking paper 50m', quantity: 8, unitPrice: 3.25, discount: 0, vatRate: null, total: 26 },
      { description: 'Piping bags 100', quantity: 4, unitPrice: 5.5, discount: 0, vatRate: null, total: 22 },
    ], 'no-vat-column');
    // Left empty rather than guessed at: the shop's own rate is applied when
    // the draft is posted, and a rate invented here would be a rate nobody
    // could trace back to the paper.
    ok('an invoice with no VAT column reads, and leaves the rate empty rather than guessing');
  }

  // ------------------------------------------------------------ a credit note
  {
    const invoice = await read('credit-note');
    assert.strictEqual(invoice.creditNote, true, 'it says what it is');
    assert.strictEqual(invoice.kind, 'out', 'so the stock goes back, not onto the shelf again');
    ok('a credit note is goods leaving, however much it looks like an invoice');
  }

  // ------------------------------------------------------- not an invoice at all
  {
    const invoice = await read('utility-bill');
    assert.strictEqual(invoice.ok, false);
    assert.strictEqual(invoice.reason, 'noTable');
    assert.ok(invoice.nearest, 'and it can say what it nearly found');
    ok('a water bill is refused, and the refusal names the line it came closest on');
  }

  // ---------------------------------------------- the one it cannot read yet
  {
    const invoice = await read('wrapped-heading');
    /*
     * A heading that wraps onto three rows is still beyond it: the fragments
     * below the line are never joined to the ones above, so the columns come
     * out wrong.
     *
     * What matters is what it does about that. It used to take the first row of
     * products for the heading, read one line with a unit price of seven
     * hundred billion euros, and offer it to the shop as an ordinary delivery.
     * Now the line is over the ceiling on line money and is dropped, so the
     * file is refused instead — which is the honest answer for a layout that
     * has not been worked out.
     */
    assert.strictEqual(invoice.ok, false, 'refused rather than half-read');
    assert.ok(
      !invoice.lines.some((line) => Math.abs(line.unitPrice || 0) > 1000000),
      'and no absurd figure survives to be imported',
    );
    ok('a three-row heading is refused outright, not imported as nonsense');
  }

  console.log(`\n${passed} checks passed.`);
})();
